extend-exclude = [
    "tests/data",
    "_version.py",
]
line-length = 100

[lint]
extend-select = [
  'UP',
]
ignore = [
]

[format]
quote-style = "single"
line-ending = "lf"
docstring-code-format = true
